nombre = input("Ingrese su Nombre: ")
edad = input("Ingrese su edad: ")
direccion = input("Direccion donde vive: ")
telefono = input("Telefono: ")
archivo = open("data2.txt", "w")
archivo.write(nombre+"\n")
archivo.write(edad+"\n")
archivo.write(direccion+"\n")
archivo.write(telefono)
archivo.close()

# Leyendo el archivo

print("**  LECTURA DEL ARCHIVO ***")
archivo = open("data2.txt")
nombre = archivo.readline()
edad = archivo.readline()
direccion = archivo.readline()
telefono  = archivo.readline()
archivo.close()
print("Nombre = ", nombre.upper())
print("Edad = ",edad)
print("Direccion = ",direccion)
print("Telefono = ",telefono)
